### ISSUE TITLE
Error thrown when logging in with bad credentials

### ISSUE THREAD

**Issue by PyUnchained** [zimscape/zimscape-cli#1]
**Description**
The following error is thrown when attempting to login through the cli when an invalid username and password combination is used:

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch()

**To Reproduce**

1. Execute  'zimscape login' in the terminal
2. Attempt to login with an invalid email address and password

**Expected behavior**
There should be a graceful warning stating that the login credentials are incorrect rather than an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/10345678/81052316-83400800-8ec3-11ea-898f-15e2fd06c600.png)

 - OS: Ubuntu 18
 - Zimscape CLI version: 0.1.0

**Comment by vusa-khoza** [comment]
Noted. Error handling on unexpected responses from an http request have been improved. Fixes published on [v0.1.1](https://npmjs.org/package/zimscape-cli).
