### ISSUE TITLE
Unable to connect to the server when executing .runfile.yml commands

### ISSUE THREAD

**Issue by PyUnchained** [zimscape/zimscape-cli#2]
**Description**
crypto/rsa: verification error thrown when .runfile.yml script runs.

**Screenshots**
![image](https://user-images.githubusercontent.com/10345678/85675249-d7968580-b6c5-11ea-8cb1-770b922053ab.png)

 - OS: Ubuntu 18
 - Zimscape CLI version: 0.2.1

**Comment by zimscape** [comment]
Hi @PyUnchained. Thanks for the post. Sorry we couldn't get to it sooner. That likely happened because of a misconfiguration on your accounts bash profile. There where some teething problems with the initial version but you should be all good now.

**Comment by zimscape** [comment]
Closing as resolved
